In [2]:
import numpy as np
import pandas as pd
from pandas_datareader import data as wb
import matplotlib.pyplot as plt

In [3]:
tickers= ['PG', 'BEI.DE']
sec_data = pd.DataFrame()

for t in tickers:
    sec_data[t]= wb.DataReader(t, data_source='yahoo', start='2007-1-1')['Adj Close']

In [4]:
sec_data.tail()

                    PG      BEI.DE
Date
2019-09-23  123.220001  107.500000
2019-09-24  123.610001  108.400002
2019-09-25  123.019997  107.250000
2019-09-26  124.309998  107.750000
2019-09-27  124.570000  108.000000

In [5]:
sec_returns=np.log(sec_data/sec_data.shift(1))
sec_returns

                  PG    BEI.DE
Date
2007-01-03       NaN       NaN
2007-01-04 -0.007621  0.006545
2007-01-05 -0.008624 -0.020772
2007-01-08  0.002202  0.000202
2007-01-09 -0.002517 -0.022858
2007-01-10  0.011901 -0.012673
2007-01-11  0.006207  0.007498
2007-01-12  0.005554  0.009295
2007-01-16  0.000000  0.024572
2007-01-17  0.010304 -0.041783
2007-01-18  0.002750  0.011025
2007-01-19  0.008357 -0.002071
2007-01-22 -0.005614 -0.000829
2007-01-23 -0.001218  0.001037
2007-01-24 -0.001982  0.013382
2007-01-25 -0.009047 -0.019619
2007-01-26 -0.000925  0.000208
2007-01-29  0.000308  0.013050
2007-01-30 -0.004480  0.026202
2007-01-31  0.004326  0.032932
2007-02-01  0.007219 -0.010923
2007-02-02  0.000000  0.007035
2007-02-05 -0.002912  0.000973
2007-02-06 -0.008633 -0.004876
2007-02-07 -0.001704 -0.000391
2007-02-08  0.001704 -0.010618
2007-02-09 -0.002480  0.001777
2007-02-12 -0.004199 -0.000987
2007-02-13  0.008536  0.001382
2007-02-14  0.002624  0.012934
...              ...       ...
2019-08-16  0.015133  0.000455
2019-08-19  0.008855  0.004535
2019-08-20 -0.011207 -0.003172
2019-08-21  0.002520  0.010386
2019-08-22  0.001844 -0.009025
2019-08-23 -0.017741 -0.001361
2019-08-26  0.016904  0.006786
2019-08-27  0.010256  0.018759
2019-08-28  0.007026  0.005296
2019-08-29 -0.001814  0.005268
2019-08-30 -0.007870  0.002624
2019-09-03  0.009355  0.012153
2019-09-04  0.015129  0.003875
2019-09-05 -0.003659 -0.016465
2019-09-06  0.000896 -0.003940
2019-09-09 -0.005713 -0.023071
2019-09-10 -0.018922 -0.014467
2019-09-11  0.011528  0.013569
2019-09-12  0.012293 -0.005857
2019-09-13 -0.005308 -0.009079
2019-09-16 -0.019598 -0.016089
2019-09-17  0.011706  0.019730
2019-09-18  0.002061 -0.007296
2019-09-19  0.004028 -0.011971
2019-09-20  0.002785 -0.003247
2019-09-23  0.007985 -0.000930
2019-09-24  0.003160  0.008337
2019-09-25 -0.004785 -0.010666
2019-09-26  0.010432  0.004651
2019-09-27  0.002089  0.002317

[3207 rows x 2 columns]

In [7]:
#calcolo il ritorno medio delle security
sec_returns['PG'].mean()

0.0003248291010333543

In [11]:
sec_returns['PG'].mean()*250

0.08120727525833858

In [12]:
sec_returns['PG'].std()
#deviazione standard

0.010968627573652679

In [13]:
#dobbiamo ora calcolare la radice di 250 e moltiplicarlo per la std
sec_returns['PG'].std()*250**0.5

0.1734292296943438

In [15]:
#posso velocizzare il procedimento con più titoli, occhio alle parentesi
sec_returns[['PG','BEI.DE']].mean()*250

PG        0.081207
BEI.DE    0.074005
dtype: float64

In [19]:
sec_returns[['PG','BEI.DE']].std() *25 **0.5

PG        0.054843
BEI.DE    0.068192
dtype: float64