In [1]:
import numpy as np
import pandas as pd

In [4]:
#creo una colonna con valori casuali 
colonna = pd.Series(np.random.random(5), name="colonna 1")
colonna

0    0.671041
1    0.739983
2    0.911893
3    0.006502
4    0.487203
Name: colonna 1, dtype: float64

In [5]:
#acceso a una riga precisa
colonna[2]

0.9118931543166028

In [3]:
from pandas_datareader import data as wb

,High,Low,Open,Close,Volume,Adj Close
Date,,,,,,
2009-01-02,62.970001,61.060001,61.689999,62.799999,11135700.0,45.009834
2009-01-05,62.439999,61.590000,62.320000,62.349998,14322800.0,44.687313
2009-01-06,62.950001,61.509998,62.500000,62.169998,13401600.0,44.558304
2009-01-07,61.660000,60.639999,61.330002,61.080002,12415600.0,43.777088
2009-01-08,61.250000,60.000000,60.910000,60.410000,11508100.0,43.296886
2009-01-09,60.799999,59.750000,60.639999,59.860001,10843200.0,42.902706
2009-01-12,60.419998,59.689999,59.750000,59.939999,11373200.0,42.960022
2009-01-13,60.290001,59.020000,59.959999,59.470001,15791900.0,42.623173
2009-01-14,59.180000,57.220001,59.049999,57.860001,16108100.0,41.469250
2009-01-15,57.480000,56.549999,57.090000,57.459999,18807200.0,41.182568
2009-01-16,58.250000,57.119999,58.080002,57.730000,18904200.0,41.376087
2009-01-20,58.450001,57.230000,57.770000,57.430000,17999300.0,41.161068
2009-01-21,58.200001,56.490002,58.200001,57.570000,18204700.0,41.550812
2009-01-22,57.560001,56.270000,57.380001,56.959999,19133700.0,41.110538
2009-01-23,56.610001,55.590000,56.540001,56.000000,21067500.0,40.417675
2009-01-26,56.919998,55.610001,55.950001,56.369999,17032100.0,40.684711
2009-01-27,57.389999,56.200001,56.480000,56.700001,11962900.0,40.922886
2009-01-28,58.380001,56.900002,57.500000,58.180000,17743200.0,41.991062
2009-01-29,59.000000,57.560001,57.790001,58.220001,14550300.0,42.019943
2009-01-30,56.840000,54.240002,56.500000,54.500000,35110700.0,39.335056
2009-02-02,54.380001,52.209999,54.000000,53.049999,19427200.0,38.288517
2009-02-03,54.090000,52.540001,53.490002,53.910000,14898500.0,38.909218
2009-02-04,54.450001,52.209999,54.330002,52.520000,14760300.0,37.905994
2009-02-05,53.599998,52.130001,52.290001,53.320000,17727500.0,38.483387
2009-02-06,54.459999,53.060001,53.419998,54.000000,15338000.0,38.974190
2009-02-09,53.980000,52.669998,53.889999,52.939999,13422200.0,38.209118
2009-02-10,53.459999,50.970001,52.740002,51.450001,22520700.0,37.133728
2009-02-11,51.910000,50.860001,51.799999,51.160000,16404400.0,36.924427
2009-02-12,51.400002,49.950001,50.930000,51.279999,18019300.0,37.011028
2009-02-13,51.680000,50.730000,51.369999,51.090000,11644800.0,36.873905
...,...,...,...,...,...,...
2019-03-22,103.150002,99.010002,102.480003,101.660004,11035900.0,100.947372
2019-03-25,102.339996,101.260002,101.660004,101.959999,6955500.0,101.245262
2019-03-26,103.480003,102.400002,102.440002,103.019997,6909400.0,102.297829
2019-03-27,103.019997,102.040001,102.760002,102.900002,6037100.0,102.178673
2019-03-28,103.680000,103.110001,103.309998,103.550003,6793700.0,102.824120
2019-03-29,104.150002,103.110001,103.860001,104.050003,7535400.0,103.320618
2019-04-01,104.230003,103.139999,104.230003,103.639999,6626500.0,102.913483
2019-04-02,104.019997,103.260002,103.610001,103.750000,6088800.0,103.022713
2019-04-03,103.889999,102.750000,103.580002,103.690002,5226500.0,102.963135
2019-04-04,103.669998,102.790001,103.480003,103.430000,4786100.0,102.704956
2019-04-05,103.690002,103.169998,103.610001,103.650002,4281800.0,102.923416
2019-04-08,105.139999,103.500000,103.930000,104.970001,8468600.0,104.234161
2019-04-09,104.760002,104.139999,104.550003,104.660004,5820300.0,103.926338
2019-04-10,105.000000,104.239998,104.660004,104.650002,5394300.0,103.916405
2019-04-11,105.050003,104.370003,104.580002,104.750000,5078400.0,104.015701
2019-04-12,105.059998,104.169998,104.750000,105.059998,6707900.0,104.323532
2019-04-15,105.779999,104.790001,104.980003,105.730003,5639200.0,104.988838
2019-04-16,106.500000,105.650002,105.980003,106.419998,8136100.0,105.673996
2019-04-17,106.510002,105.349998,106.269997,105.849998,6778100.0,105.849998
2019-04-18,106.709999,105.830002,106.019997,106.050003,7248900.0,106.050003
2019-04-22,107.199997,105.739998,106.129997,106.010002,9057200.0,106.010002
2019-04-23,104.110001,102.129997,104.010002,103.160004,15979800.0,103.160004
2019-04-24,104.650002,102.790001,103.320000,103.690002,10094800.0,103.690002
2019-04-25,103.570000,102.589996,103.099998,103.279999,6085300.0,103.279999
2019-04-26,105.879997,103.910004,103.949997,105.860001,7747400.0,105.860001
2019-04-29,105.750000,104.720001,105.570000,104.779999,4787600.0,104.779999
2019-04-30,106.620003,104.660004,104.860001,106.480003,8251300.0,106.480003
2019-05-01,106.389999,104.809998,106.150002,104.930000,6733800.0,104.930000
2019-05-02,105.760002,105.050003,105.199997,105.559998,6270300.0,105.559998
2019-05-03,106.410004,105.580002,105.989998,106.080002,4793400.0,106.080002

In [5]:
PG.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2601 entries, 2009-01-02 to 2019-05-03
Data columns (total 6 columns):
High         2601 non-null float64
Low          2601 non-null float64
Open         2601 non-null float64
Close        2601 non-null float64
Volume       2601 non-null float64
Adj Close    2601 non-null float64
dtypes: float64(6)
memory usage: 142.2 KB

In [8]:
import pandas as pd
tickers= ['PG', 'MSFT', 'AAPL', 'T']
new_data = pd.DataFrame()
for t in tickers:
    new_data[t] = wb.DataReader(t, data_source='iex', start='2017-1-1')['close']

new_data

                  PG      MSFT      AAPL        T
date
2017-01-03   77.7003   59.9156  112.1398  37.4510
2017-01-04   77.9771   59.6476  112.0143  37.2334
2017-01-05   78.4939   59.6476  112.5839  37.1289
2017-01-06   78.4662   60.1646  113.8391  36.3891
2017-01-09   77.8848   59.9731  114.8818  35.9312
2017-01-10   77.0451   59.9539  114.9976  35.9400
2017-01-11   77.2850   60.4997  115.6155  35.7639
2017-01-12   77.3681   59.9444  115.1328  36.1161
2017-01-13   77.5249   60.0305  114.9300  36.0721
2017-01-17   78.6323   59.8678  115.8569  36.2042
2017-01-18   78.9946   59.8390  115.8472  35.9312
2017-01-19   78.7807   59.6476  115.6445  36.1073
2017-01-20   81.3385   60.0688  115.8569  36.5036
2017-01-23   80.8827   60.2795  115.9341  36.9880
2017-01-24   81.7198   60.8156  115.8279  36.4244
2017-01-25   81.0687   60.9688  117.6720  36.4508
2017-01-26   80.5479   61.5337  117.7299  36.7854
2017-01-27   80.6595   62.9794  117.7396  36.9968
2017-01-30   80.6874   62.3571  117.4306  36.8295
2017-01-31   81.4780   61.8975  117.1603  37.1289
2017-02-01   81.2269   60.8731  124.3048  37.0408
2017-02-02   81.6268   60.4805  124.0924  36.2659
2017-02-03   81.3013   60.9688  124.6234  36.3275
2017-02-06   81.2920   60.9305  125.7916  36.1602
2017-02-07   81.8593   60.7294  126.9888  36.2130
2017-02-08   82.1570   60.6433  127.4812  36.2923
2017-02-09   82.4732   61.3326  128.4024  36.3803
2017-02-10   81.8221   61.2752  128.1115  36.4420
2017-02-13   82.1384   61.9645  129.2460  35.7991
2017-02-14   81.7198   62.1957  130.9235  35.8872
...              ...       ...       ...      ...
2019-03-22  100.9475  117.0500  191.0500  30.5808
2019-03-25  101.2454  117.6600  188.7400  30.2855
2019-03-26  102.2979  117.9100  186.7900  30.8957
2019-03-27  102.1788  116.7700  188.4700  30.9056
2019-03-28  102.8242  116.9300  188.7200  30.5217
2019-03-29  103.3207  117.9400  189.9500  30.8662
2019-04-01  102.9136  119.0200  191.2400  31.4469
2019-04-02  103.0228  119.1900  194.0200  31.1320
2019-04-03  102.9632  119.9700  195.3500  31.3682
2019-04-04  102.7051  119.3600  195.6900  31.4764
2019-04-05  102.9235  119.8900  197.0000  31.8406
2019-04-08  104.2343  119.9300  200.1000  31.8800
2019-04-09  103.9264  119.2800  199.5000  31.7500
2019-04-10  103.9165  120.1900  200.6200  31.8800
2019-04-11  104.0158  120.3300  198.9500  32.2000
2019-04-12  104.3236  120.9500  198.8700  32.2000
2019-04-15  104.9889  121.0500  199.2300  32.0200
2019-04-16  105.6741  120.7700  199.2500  32.2500
2019-04-17  105.8500  121.7700  203.1300  31.9500
2019-04-18  106.0500  123.3700  203.8600  32.0300
2019-04-22  106.0100  123.7600  204.5300  32.0800
2019-04-23  103.1600  125.4400  207.4800  32.1000
2019-04-24  103.6900  125.0100  207.1600  30.7900
2019-04-25  103.2800  129.1500  205.2800  30.3400
2019-04-26  105.8600  129.8900  204.3000  30.6800
2019-04-29  104.7800  129.7700  204.6100  30.8800
2019-04-30  106.4800  130.6000  200.6700  30.9600
2019-05-01  104.9300  127.8800  210.5200  30.7900
2019-05-02  105.5600  126.2100  209.1500  30.6200
2019-05-03  106.0800  128.9000  211.7500  30.7000

[587 rows x 4 columns]