In [1]:
import numpy as np
import pandas as pd
from pandas_datareader import data as wb
import matplotlib.pyplot as plt

In [19]:
tickers= ['PG', 'BEI.DE','AAPL']
sec_data = pd.DataFrame()

for t in tickers:
    sec_data[t]= wb.DataReader(t, data_source='yahoo', start='2015-1-1')['Adj Close']

In [20]:
sec_returns=np.log(sec_data/sec_data.shift(1))
sec_returns

                  PG    BEI.DE      AAPL
Date
2015-01-02       NaN       NaN       NaN
2015-01-05 -0.004766 -0.016229 -0.028576
2015-01-06 -0.004565  0.003327  0.000094
2015-01-07  0.005232  0.009168  0.013925
2015-01-08  0.011371  0.030790  0.037703
2015-01-09 -0.009374 -0.011527  0.001072
2015-01-12 -0.003663  0.025215 -0.024949
2015-01-13  0.004217  0.002430  0.008839
2015-01-14 -0.003439 -0.000286 -0.003818
2015-01-15 -0.001446  0.054465 -0.027516
2015-01-16  0.015350  0.015032 -0.007801
2015-01-20 -0.000658  0.000799  0.025431
2015-01-21  0.002030  0.006104  0.007605
2015-01-22  0.009761  0.012098  0.025683
2015-01-23 -0.016951  0.023509  0.005147
2015-01-26 -0.005566  0.004585  0.001062
2015-01-27 -0.035103 -0.012403 -0.035641
2015-01-28 -0.015615 -0.000129  0.054993
2015-01-29  0.006088  0.009605  0.030659
2015-01-30 -0.016239 -0.008447 -0.014742
2015-02-02  0.009799  0.006151  0.012469
2015-02-03  0.009704 -0.016617  0.000169
2015-02-04 -0.001863  0.006602  0.007640
2015-02-05  0.010551  0.000645  0.007112
2015-02-06 -0.012652 -0.003746 -0.008457
2015-02-09 -0.006563 -0.012110  0.006621
2015-02-10  0.003990  0.003009  0.019029
2015-02-11  0.002923 -0.001045  0.023168
2015-02-12  0.004543  0.007814  0.012573
2015-02-13 -0.001512 -0.024028  0.004891
...              ...       ...       ...
2019-08-16  0.015133  0.000455  0.023321
2019-08-19  0.008855  0.004535  0.018472
2019-08-20 -0.011207 -0.003172  0.000048
2019-08-21  0.002520  0.010386  0.010780
2019-08-22  0.001844 -0.009025 -0.000847
2019-08-23 -0.017741 -0.001361 -0.047323
2019-08-26  0.016904  0.006786  0.018821
2019-08-27  0.010256  0.018759 -0.011348
2019-08-28  0.007026  0.005296  0.006688
2019-08-29 -0.001814  0.005268  0.016790
2019-08-30 -0.007870  0.002624 -0.001293
2019-09-03  0.009355  0.012153 -0.014671
2019-09-04  0.015129  0.003875  0.016824
2019-09-05 -0.003659 -0.016465  0.019363
2019-09-06  0.000896 -0.003940 -0.000094
2019-09-09 -0.005713 -0.023071  0.004258
2019-09-10 -0.018922 -0.014467  0.011744
2019-09-11  0.011528  0.013569  0.031300
2019-09-12  0.012293 -0.005857 -0.002239
2019-09-13 -0.005308 -0.009079 -0.019646
2019-09-16 -0.019598 -0.016089  0.005243
2019-09-17  0.011706  0.019730  0.003631
2019-09-18  0.002061 -0.007296  0.009336
2019-09-19  0.004028 -0.011971 -0.008158
2019-09-20  0.002785 -0.003247 -0.014726
2019-09-23  0.007985 -0.000930  0.004537
2019-09-24  0.003160  0.008337 -0.004766
2019-09-25 -0.004785 -0.010666  0.015272
2019-09-26  0.010432  0.004651 -0.005171
2019-09-27  0.002089  0.002317 -0.004878

[1193 rows x 3 columns]

In [4]:
#calcolo della varianza di una singola azione
PG_var= sec_returns['PG'].var()
PG_var

0.00012031079084949386

In [5]:
PG_var_a= sec_returns['PG'].var()*250
PG_var_a

0.030077697712373466

In [11]:
BEI_var_a= sec_returns['BEI.DE'].var()*250
BEI_var_a

0.0465016762552354

In [15]:
#calcolo della covarianza delle due azioni, sulla diagonale le singole azioni, sulla parte 
#triangolare la loro covarianza
#con questa matrice posso bypassare i calcoli della varianza iniziale
cov_matrix_a= sec_returns.cov()*250
cov_matrix_a

              PG    BEI.DE      AAPL
PG      0.030078  0.009760  0.017154
BEI.DE  0.009760  0.046502  0.013162
AAPL    0.017154  0.013162  0.098295

In [16]:
#ora calcoliamo la loro correlazione
corr_matrix= sec_returns.corr()
corr_matrix

              PG    BEI.DE      AAPL
PG      1.000000  0.260996  0.315488
BEI.DE  0.260996  1.000000  0.194220
AAPL    0.315488  0.194220  1.000000